const db = require('./database');

const questions = [
  // Frontend Developer - id 1
  { it_role_id: 1, text: "What excites you most about the result of your work?", answer_option_a: "When what I built looks great and feels smooth in the browser", answer_option_b: "When the system processes data quickly and without errors", answer_option_c: "When the user instinctively knows what to do" },
  { it_role_id: 1, text: "How do you spend your free time at the computer?", answer_option_a: "I browse cool websites and think about how they were built technically", answer_option_b: "I study new algorithms or read about system architecture", answer_option_c: "I sketch layouts or browse design galleries for inspiration" },
  { it_role_id: 1, text: "Which type of task do you enjoy the most?", answer_option_a: "Turning a static mockup into a living, interactive interface", answer_option_b: "Designing database schemas and entity relationships", answer_option_c: "Finding patterns in data and building charts" },
  { it_role_id: 1, text: "When you use a new app, what do you notice first?", answer_option_a: "How smooth the animations and transitions feel", answer_option_b: "How fast the app responds to requests", answer_option_c: "How logical the layout is and how clear the interface is" },
  { it_role_id: 1, text: "Which learning approach suits you best?", answer_option_a: "Building something visible right away — a page, a button, an effect", answer_option_b: "Understanding the theory first, then applying it in practice", answer_option_c: "Watching how other people use the product and learning from that" },
  { it_role_id: 1, text: "What motivates you most at work?", answer_option_a: "Seeing the tangible result of my work rendered in a browser", answer_option_b: "Solving complex technical problems under the hood", answer_option_c: "Knowing the product solves a real problem for users" },
  { it_role_id: 1, text: "How do you react to criticism of your work?", answer_option_a: "I look at how to improve the visual or interactive part of the interface", answer_option_b: "I analyze where the logical error was in the code", answer_option_c: "I think about how to make the product clearer for the user" },
  { it_role_id: 1, text: "What type of documentation do you find most interesting to read?", answer_option_a: "Docs for CSS libraries, animation tools, and UI component systems", answer_option_b: "Docs for APIs, databases, and server-side frameworks", answer_option_c: "UX guidelines and user behavior research" },
  { it_role_id: 1, text: "What matters most when choosing a technology for a project?", answer_option_a: "How well it supports modern visual capabilities", answer_option_b: "How performant and scalable it is", answer_option_c: "How easy it is to work with and how widely adopted it is" },
  { it_role_id: 1, text: "Which of these activities brings you joy?", answer_option_a: "Building responsive layouts so a site looks perfect on any device", answer_option_b: "Optimizing a SQL query to run ten times faster", answer_option_c: "Running an A/B test and analyzing which variant performs better" },
  { it_role_id: 1, text: "What do you most often discuss with colleagues?", answer_option_a: "New CSS features, component libraries, and browser compatibility", answer_option_b: "Microservice architecture, design patterns, and system reliability", answer_option_c: "Product metrics, user behavior, and hypotheses" },
  { it_role_id: 1, text: "How do you feel about design systems?", answer_option_a: "Very important — I want to be involved in building and maintaining components", answer_option_b: "Useful to know, but not really my area of responsibility", answer_option_c: "I'd rather create the visual rules and language of the system itself" },
  { it_role_id: 1, text: "Which description best fits your ideal workday?", answer_option_a: "I built a great interactive element that the team loved", answer_option_b: "I fixed a server-side bug that the team had been chasing for days", answer_option_c: "I ran user interviews and got valuable insights" },
  { it_role_id: 1, text: "What annoys you most about your work?", answer_option_a: "When the design is sloppy or impossible to implement correctly", answer_option_b: "When there's no clear architecture and everything is written chaotically", answer_option_c: "When decisions are made without data or logical reasoning" },
  { it_role_id: 1, text: "What superpower would you want in your work?", answer_option_a: "Building any interface perfectly and quickly with no bugs", answer_option_b: "Instantly designing reliable and scalable systems", answer_option_c: "Accurately predicting user behavior from data" },
  { it_role_id: 1, text: "How do you relate to perfectionism at work?", answer_option_a: "I want every pixel and animation to be exactly as intended", answer_option_b: "It's important that code is clean and logical, not just functional", answer_option_c: "It's important that the product solves the problem, not that it looks perfect" },
  { it_role_id: 1, text: "How do you feel about cross-browser compatibility?", answer_option_a: "It's an important part of the job — I'm happy to dig into browser quirks", answer_option_b: "It's a headache I'd rather avoid", answer_option_c: "It's a technical concern — I'm more interested in user behavior" },
  { it_role_id: 1, text: "Which project would you be most proud of?", answer_option_a: "An interactive landing page with smooth animations and great performance", answer_option_b: "A high-load API handling millions of requests per day", answer_option_c: "An app that meaningfully improved the lives of real people" },
  { it_role_id: 1, text: "What do you do right after your code hits production?", answer_option_a: "I check how it looks across different browsers and devices", answer_option_b: "I watch the logs and server performance metrics", answer_option_c: "I see how users react and what they say" },
  { it_role_id: 1, text: "How do you explain your job to someone outside tech?", answer_option_a: "I build everything you see on a website — buttons, menus, animations", answer_option_b: "I build what works behind the scenes — logic, databases, servers", answer_option_c: "I think about what the product should be like to make it easy to use" },

  // Backend Developer - id 2
  { it_role_id: 2, text: "What attracts you most about programming?", answer_option_a: "Designing logic that runs under the hood and processes data", answer_option_b: "Creating beautiful interfaces that users interact with", answer_option_c: "Analyzing data and drawing conclusions from statistics" },
  { it_role_id: 2, text: "Which type of task gives you the most satisfaction?", answer_option_a: "Optimizing database queries and speeding up the system", answer_option_b: "Making an animation or page effect perfectly smooth", answer_option_c: "Running tests and finding hidden issues in the product" },
  { it_role_id: 2, text: "How do you feel about working with data?", answer_option_a: "I love designing data structures and thinking about how to store them", answer_option_b: "I prefer working with data at the display layer in the interface", answer_option_c: "I love analyzing data and drawing insights from it" },
  { it_role_id: 2, text: "What excites you most on the technical side?", answer_option_a: "System architecture, design patterns, and scalability", answer_option_b: "Modern CSS capabilities and visual possibilities in browsers", answer_option_c: "Testing methodologies and quality assurance" },
  { it_role_id: 2, text: "How do you prefer to handle errors?", answer_option_a: "Digging into the root cause through logs and stack traces", answer_option_b: "Fixing visual bugs in the interface", answer_option_c: "Systematically reproducing and documenting the problem" },
  { it_role_id: 2, text: "What matters most to you in code?", answer_option_a: "Reliability, performance, and architectural cleanliness", answer_option_b: "Readability and a well-structured component design", answer_option_c: "Test coverage and predictable behavior" },
  { it_role_id: 2, text: "Which style of collaboration with the team suits you best?", answer_option_a: "Technical architecture discussions and deep code reviews", answer_option_b: "Collaborating on design and interface implementation", answer_option_c: "Discussing requirements and defining acceptance criteria" },
  { it_role_id: 2, text: "What fascinates you about technology?", answer_option_a: "How massive systems handle millions of requests simultaneously", answer_option_b: "How browsers render complex animations so quickly", answer_option_c: "How machine learning algorithms find patterns in data" },
  { it_role_id: 2, text: "How do you react when the product goes down in production?", answer_option_a: "I immediately check logs, error traces, and server metrics", answer_option_b: "I check how it looks for the user in the browser", answer_option_c: "I write a bug report with detailed steps to reproduce" },
  { it_role_id: 2, text: "What motivates you in the long run?", answer_option_a: "Building systems that run reliably for years without failure", answer_option_b: "Creating interfaces that people find beautiful", answer_option_c: "Helping teams ship quality products consistently" },
  { it_role_id: 2, text: "What kind of documentation do you prefer writing?", answer_option_a: "Technical API docs and architectural diagrams", answer_option_b: "Storybook stories or guides on how to use components", answer_option_c: "Test cases and feature verification checklists" },
  { it_role_id: 2, text: "How do you approach a new project?", answer_option_a: "I start by designing the database schema and API contracts", answer_option_b: "I start by looking at the design and thinking about how to implement it", answer_option_c: "I start by studying requirements and writing test scenarios" },
  { it_role_id: 2, text: "What's important to you in a work environment?", answer_option_a: "Challenging problems, good tooling, and freedom in choosing solutions", answer_option_b: "Close collaboration with designers and the product team", answer_option_c: "Clear processes and shared accountability for quality" },
  { it_role_id: 2, text: "What do you read in your spare time?", answer_option_a: "Articles about system architecture, databases, and DevOps", answer_option_b: "Blogs about web animation, design systems, and browser APIs", answer_option_c: "Content about testing, automation, and quality practices" },
  { it_role_id: 2, text: "How do you think about security?", answer_option_a: "It's directly my responsibility — authentication, encryption, data protection", answer_option_b: "It's important, but mostly handled by a different team", answer_option_c: "Security vulnerabilities should be caught as part of testing" },
  { it_role_id: 2, text: "Which programming language appeals to you most?", answer_option_a: "Go, Rust, Java, or Python for server-side development", answer_option_b: "JavaScript or TypeScript for interactive interfaces", answer_option_c: "SQL and Python for working with data" },
  { it_role_id: 2, text: "How do you feel when working in a team?", answer_option_a: "I enjoy being the server-side expert and helping others navigate it", answer_option_b: "I love discussing visual solutions and how to implement them", answer_option_c: "I make sure everyone understands the quality criteria" },
  { it_role_id: 2, text: "What does a job well done mean to you?", answer_option_a: "The system is stable, fast, and easy to scale", answer_option_b: "The interface looks exactly like the design and runs smoothly", answer_option_c: "All scenarios are tested and bugs are documented" },
  { it_role_id: 2, text: "How do you conduct a code review?", answer_option_a: "I look at architecture, performance, and potential vulnerabilities", answer_option_b: "I check readability and whether the component approach is consistent", answer_option_c: "I look for missing edge cases and insufficient test coverage" },
  { it_role_id: 2, text: "If you were building your own startup, what would you focus on?", answer_option_a: "Building a reliable and scalable technical infrastructure", answer_option_b: "Creating a beautiful and user-friendly product interface", answer_option_c: "Understanding users deeply and building quality processes" },

  // Data Analyst - id 3
  { it_role_id: 3, text: "What attracts you most about working with information?", answer_option_a: "Finding patterns and drawing conclusions from large volumes of data", answer_option_b: "Structuring data into a convenient form for the user", answer_option_c: "Checking data for correctness and hunting down inconsistencies" },
  { it_role_id: 3, text: "Which type of task do you enjoy most?", answer_option_a: "Building dashboards and visualizations that make complex things simple", answer_option_b: "Developing interactive elements to display data in the UI", answer_option_c: "Verifying that data flows correctly between systems" },
  { it_role_id: 3, text: "How do you make decisions in everyday life?", answer_option_a: "I rely on facts and try to find data to confirm or disprove an idea", answer_option_b: "I trust my intuition and past experience", answer_option_c: "I test several options and pick the one that works without issues" },
  { it_role_id: 3, text: "What makes you most proud at the end of a project?", answer_option_a: "When the analysis helped make the right business decision", answer_option_b: "When the product looks great and works without bugs", answer_option_c: "When users say the product is easy and enjoyable to use" },
  { it_role_id: 3, text: "How do you feel about numbers and statistics?", answer_option_a: "I love working with them — it's my native language", answer_option_b: "It's a useful tool, but not the most exciting part of the job", answer_option_c: "I use them when needed, but prefer qualitative methods" },
  { it_role_id: 3, text: "How do you spend your free time?", answer_option_a: "Reading about statistics and following interesting research", answer_option_b: "Browsing cool websites and trying to recreate something similar", answer_option_c: "Testing new apps and noticing bugs and inconveniences" },
  { it_role_id: 3, text: "What frustrates you most at work?", answer_option_a: "When decisions are made without data or in spite of it", answer_option_b: "When the design is implemented carelessly or incorrectly", answer_option_c: "When a product ships with defects that could have been caught earlier" },
  { it_role_id: 3, text: "Which tool would you learn first?", answer_option_a: "Python or R and SQL for data analysis", answer_option_b: "React or Vue for building modern interfaces", answer_option_c: "Selenium or another tool for test automation" },
  { it_role_id: 3, text: "How do you explain complex things to colleagues?", answer_option_a: "I build clear charts and tables that speak for themselves", answer_option_b: "I show a working prototype or demo", answer_option_c: "I describe reproduction steps or write a clear instruction" },
  { it_role_id: 3, text: "What interests you about business?", answer_option_a: "How customer behavior data influences company strategy", answer_option_b: "How technology enables the creation of new products", answer_option_c: "How to build processes that make the product reliable" },
  { it_role_id: 3, text: "How do you feel in situations of uncertainty?", answer_option_a: "I try to collect data to reduce the uncertainty", answer_option_b: "I start doing something and adjust as I go", answer_option_c: "I try to map out all possible scenarios in advance" },
  { it_role_id: 3, text: "What do you value in teamwork?", answer_option_a: "Sharing insights from data and helping the team make better decisions", answer_option_b: "Implementing others ideas and watching them come to life", answer_option_c: "Being the voice of quality and keeping the team from rushing" },
  { it_role_id: 3, text: "What makes a project truly interesting for you?", answer_option_a: "Lots of data, complex dependencies, and non-obvious conclusions", answer_option_b: "A technically challenging task with a beautiful result", answer_option_c: "A product that real people use and give feedback on" },
  { it_role_id: 3, text: "How do you react to unexpected results?", answer_option_a: "I dig deeper to understand the cause of the anomaly", answer_option_b: "I check if there is a bug in the code or configuration", answer_option_c: "I reproduce the situation and document it for the team" },
  { it_role_id: 3, text: "What superpower would you want?", answer_option_a: "Instantly seeing cause-and-effect relationships in data", answer_option_b: "Implementing any interface perfectly on the first try", answer_option_c: "Finding any bug before it reaches the user" },
  { it_role_id: 3, text: "How do you feel about presentations and reports?", answer_option_a: "I love telling stories through data and persuading an audience", answer_option_b: "I would rather show a working product than slides", answer_option_c: "I prefer to describe problems clearly and systematically" },
  { it_role_id: 3, text: "What do you do when you encounter an interesting product?", answer_option_a: "I think about what data they are collecting and how they are using it", answer_option_b: "I notice how the interface is built and what technologies are used", answer_option_c: "I immediately start spotting flaws and inconveniences" },
  { it_role_id: 3, text: "What matters most when working under deadline pressure?", answer_option_a: "Delivering a quality analysis even if it means simplifying the scope", answer_option_b: "Shipping a working version and iterating later", answer_option_c: "Making sure what ships does not have critical errors" },
  { it_role_id: 3, text: "How do you feel in an expert role?", answer_option_a: "I enjoy being the source of data insights and analytical clarity for the team", answer_option_b: "I love being the technical implementation expert", answer_option_c: "I care most about being the expert on quality and reliability" },
  { it_role_id: 3, text: "Which project would you be most proud of?", answer_option_a: "An analysis that saved the company millions or revealed a new opportunity", answer_option_b: "A product that is technically complex and beautiful at the same time", answer_option_c: "A product that shipped without a single critical bug" },

  // QA Engineer - id 4
  { it_role_id: 4, text: "What draws your attention most when using a new product?", answer_option_a: "I immediately start looking for errors, inconsistencies, and unexpected behavior", answer_option_b: "I notice the visual design and interface details", answer_option_c: "I think about how it works technically under the hood" },
  { it_role_id: 4, text: "How do you feel about details and small things?", answer_option_a: "Details are critical — that is exactly where the most serious problems hide", answer_option_b: "Details matter visually, but you should not get obsessed with them", answer_option_c: "It is important to look at the big picture, not get lost in the details" },
  { it_role_id: 4, text: "What gives you the most satisfaction at work?", answer_option_a: "When I find a bug that nobody else noticed", answer_option_b: "When I implement a beautiful and technically complex interface", answer_option_c: "When data confirms my hypothesis" },
  { it_role_id: 4, text: "How do you behave when something goes wrong?", answer_option_a: "I methodically reproduce the situation, document the steps, and find the pattern", answer_option_b: "I open the console and look for a technical error", answer_option_c: "I analyze data to understand where the failure occurred" },
  { it_role_id: 4, text: "What do you value most in teamwork?", answer_option_a: "Being the one who protects users from a low-quality product", answer_option_b: "Making a technical contribution to the product implementation", answer_option_c: "Helping the team make decisions based on data" },
  { it_role_id: 4, text: "How do you feel about processes and standards?", answer_option_a: "Clear processes are good — they help ensure nothing is missed", answer_option_b: "I prefer flexibility and the ability to act based on the situation", answer_option_c: "Processes matter, but results matter more" },
  { it_role_id: 4, text: "What quality do you consider your biggest strength?", answer_option_a: "Attentiveness and the ability to notice what others miss", answer_option_b: "Technical depth and the ability to solve complex problems", answer_option_c: "Analytical thinking and working with data" },
  { it_role_id: 4, text: "How do you react when a new product update is released?", answer_option_a: "First thing I check whether anything that worked before is now broken", answer_option_b: "I look at how the new features are implemented technically", answer_option_c: "I analyze how the changes affected usage metrics" },
  { it_role_id: 4, text: "What frustrates you most?", answer_option_a: "When the team rushes and ships a product with obvious bugs", answer_option_b: "When there is no clear architecture and the code is hard to maintain", answer_option_c: "When decisions are made without data or justification" },
  { it_role_id: 4, text: "How do you approach a new task?", answer_option_a: "I first think about what could go wrong and what edge cases exist", answer_option_b: "I start implementing and solve problems as they come up", answer_option_c: "I first gather data and build context understanding" },
  { it_role_id: 4, text: "What does quality mean to you?", answer_option_a: "The product does exactly what the user expects, in every scenario", answer_option_b: "The code is clean, efficient, and easy to maintain", answer_option_c: "The product achieves its business metrics and solves real problems" },
  { it_role_id: 4, text: "How do you feel about repetitive tasks?", answer_option_a: "If routine is needed for quality, I am happy to automate and maintain it", answer_option_b: "I try to minimize routine through good architecture", answer_option_c: "Routine tasks are not for me — I prefer analytical work" },
  { it_role_id: 4, text: "How do you learn best?", answer_option_a: "Through practice — try, fail, and find the pattern", answer_option_b: "Through creation — building a project from scratch and learning along the way", answer_option_c: "Through data — reading research and studying real-world examples" },
  { it_role_id: 4, text: "What matters most when evaluating a product?", answer_option_a: "How stable and predictably it works", answer_option_b: "How modern and visually appealing it looks", answer_option_c: "How well it actually solves the user's problem" },
  { it_role_id: 4, text: "How would you describe your thinking style?", answer_option_a: "Critical thinking — I always look for weak spots", answer_option_b: "Constructive thinking — I build and create", answer_option_c: "Analytical thinking — I look for patterns and causes" },
  { it_role_id: 4, text: "What do you think about automation?", answer_option_a: "Automated testing is one of the most valuable things in software development", answer_option_b: "Automated deployments and CI/CD pipelines matter most", answer_option_c: "Automating data analysis opens up enormous possibilities" },
  { it_role_id: 4, text: "How do you interact with the development team?", answer_option_a: "I am their quality partner — we make the product better together", answer_option_b: "I am one of the developers — we solve problems together", answer_option_c: "I provide them with data so they can make better decisions" },
  { it_role_id: 4, text: "What makes a project truly successful?", answer_option_a: "When the product runs stably and users do not run into problems", answer_option_b: "When the code is scalable and technically excellent", answer_option_c: "When the metrics show real growth and value" },
  { it_role_id: 4, text: "How do you handle deadline pressure?", answer_option_a: "I insist on the minimum necessary testing even under pressure", answer_option_b: "I focus on the critical functionality and ship an MVP", answer_option_c: "I rely on data to prioritize what matters most" },
  { it_role_id: 4, text: "How do you see your contribution to the team?", answer_option_a: "I am the last line of defense that keeps bugs from reaching users", answer_option_b: "I build the reliable technical foundation the whole product stands on", answer_option_c: "I help the team see the full picture through data" },

  // UX/UI Designer - id 5
  { it_role_id: 5, text: "What interests you most about building products?", answer_option_a: "How to make the experience as clear and enjoyable as possible", answer_option_b: "How to technically implement a beautiful interface in code", answer_option_c: "How user data can help improve the product" },
  { it_role_id: 5, text: "What do you notice first when using a new app?", answer_option_a: "How logical and intuitive the user journey is", answer_option_b: "How technically polished the animations and transitions are", answer_option_c: "How many unnecessary steps there are and where someone could make a mistake" },
  { it_role_id: 5, text: "What inspires you most?", answer_option_a: "Watching how people interact with a product and finding insights", answer_option_b: "Implementing technically complex and beautiful solutions", answer_option_c: "Analyzing funnels and user behavior metrics" },
  { it_role_id: 5, text: "How do you spend your free time?", answer_option_a: "Studying good and bad design examples and collecting references", answer_option_b: "Trying out new technologies and working on side projects", answer_option_c: "Reading about behavioral psychology and UX research" },
  { it_role_id: 5, text: "What does a good product mean to you?", answer_option_a: "One that is enjoyable to use and solves the problem with minimal effort", answer_option_b: "One that is technically reliable and works without failures", answer_option_c: "One that achieves its business metrics" },
  { it_role_id: 5, text: "How do you prefer to work with the team?", answer_option_a: "I collaborate closely with developers and researchers, bridging both worlds", answer_option_b: "I work autonomously on the technical side and communicate through tickets", answer_option_c: "I conduct research and share findings with the team" },
  { it_role_id: 5, text: "What makes you most proud at the end of a finished project?", answer_option_a: "When users say the product is easy and enjoyable to use", answer_option_b: "When the system runs stably with no complaints", answer_option_c: "When conversion rates or other metrics improved" },
  { it_role_id: 5, text: "How do you feel about user research?", answer_option_a: "It is the foundation of good design — you cannot make decisions without it", answer_option_b: "It is useful, but my job is implementation, not research", answer_option_c: "Research data is a great complement to quantitative analytics" },
  { it_role_id: 5, text: "Which tool would you learn first?", answer_option_a: "Figma, Sketch, or another prototyping tool", answer_option_b: "A modern framework for building user interfaces", answer_option_c: "Analytics and A/B testing tools" },
  { it_role_id: 5, text: "What frustrates you about bad products?", answer_option_a: "When it is unclear what to tap and you have to think about how to use it", answer_option_b: "When the product is slow or works unreliably", answer_option_c: "When there is no clear logic and everything feels chaotic" },
  { it_role_id: 5, text: "How do you make design decisions?", answer_option_a: "I rely on research, established patterns, and UX principles", answer_option_b: "I look at technical constraints and what is feasible", answer_option_c: "I look at data — what converts better and retains users longer" },
  { it_role_id: 5, text: "What matters more to you — beauty or usability?", answer_option_a: "Usability comes first, but great design unites both", answer_option_b: "Ease of implementation matters more than aesthetics", answer_option_c: "What works according to data matters more than what looks good" },
  { it_role_id: 5, text: "How do you approach user feedback?", answer_option_a: "It is gold — that is where the best design ideas are hiding", answer_option_b: "It is useful, but stability and performance are better indicators", answer_option_c: "It is important, but I trust quantitative data more" },
  { it_role_id: 5, text: "How would you describe your creative process?", answer_option_a: "Research → prototype → test → iterate", answer_option_b: "Plan → write code → refactor → deploy", answer_option_c: "Collect data → analyze → form a hypothesis → validate" },
  { it_role_id: 5, text: "What motivates you in the long run?", answer_option_a: "Making digital products that people enjoy using", answer_option_b: "Building technically excellent and scalable systems", answer_option_c: "Helping businesses make better decisions through data" },
  { it_role_id: 5, text: "How do you feel at the intersection of business and technology?", answer_option_a: "I love being the bridge between people's needs and technical possibilities", answer_option_b: "I focus on the technical side — business is not really my domain", answer_option_c: "I am drawn to the business side — numbers, strategy, growth" },
  { it_role_id: 5, text: "What do you think about accessibility?", answer_option_a: "It is a required part of good design, not an optional extra", answer_option_b: "It is important, but more of an add-on after the main work is done", answer_option_c: "It is interesting to study from the perspective of different user group behaviors" },
  { it_role_id: 5, text: "Which project would you be most proud of?", answer_option_a: "A redesign that noticeably improved the user experience and satisfaction", answer_option_b: "A technically complex product with high performance", answer_option_c: "A project that showed significant conversion growth based on data" },
  { it_role_id: 5, text: "How do you react to criticism of your work?", answer_option_a: "I see it as an opportunity to improve the product for users", answer_option_b: "I analyze it from a technical standpoint and look for a better solution", answer_option_c: "I check whether data supports the criticism" },
  { it_role_id: 5, text: "If you were building your own product, where would you start?", answer_option_a: "With user research to understand their real needs", answer_option_b: "With choosing a technology stack and defining the architecture", answer_option_c: "With market analysis and data about the target audience" }
];

const insert = db.prepare(`
  INSERT INTO question (text, answer_option_a, answer_option_b, answer_option_c, it_role_id)
  VALUES (@text, @answer_option_a, @answer_option_b, @answer_option_c, @it_role_id)
`);

const insertMany = db.transaction((questions) => {
  for (const q of questions) insert.run(q);
});

insertMany(questions);
console.log('100 questions added successfully!');